monolog:
    handlers:
        import_products:
            level: error
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-import_products.log"
            channels: [import_products]
